/**
 * This client was automatically generated by RudderStack Typewriter. ** Do Not Edit **
 */

import Foundation

class Dimensions: TypewriterSerializable {
    var height: Decimal
    var length: Decimal
    var width: Decimal

    init(height: Decimal, length: Decimal, width: Decimal) {
        self.height = height
        self.length = length
        self.width = width
    }

    func serializableDictionary() -> [String: Any] {
        var properties = [String: Any]()
        properties["height"] = self.height;
        properties["length"] = self.length;
        properties["width"] = self.width;

        return properties;
    }
}