/**
 * This client was automatically generated by RudderStack Typewriter. ** Do Not Edit **
 */

import Foundation

protocol TypewriterSerializable {
    func serializableDictionary() -> [String: Any];
}
