/**
 * This client was automatically generated by RudderStack Typewriter. ** Do Not Edit **
 */

#import <Foundation/Foundation.h>
#import "RSTypewriterSerializable.h"
#import "RSTypewriterUtils.h"

@interface RSDimensions : NSObject<RSTypewriterSerializable>

@property (strong, nonatomic, nonnull) NSNumber *height;
@property (strong, nonatomic, nonnull) NSNumber *length;
@property (strong, nonatomic, nonnull) NSNumber *width;

+(nonnull instancetype) initWithHeight:(nonnull NSNumber *)height
length:(nonnull NSNumber *)length
width:(nonnull NSNumber *)width;

-(nonnull NSDictionary<NSString *, id> *) toDictionary;

@end
