/**
 * This client was automatically generated by RudderStack Typewriter. ** Do Not Edit **
 */

#import "RSDimensions.h"

@implementation RSDimensions

+(nonnull instancetype) initWithHeight:(nonnull NSNumber *)height
length:(nonnull NSNumber *)length
width:(nonnull NSNumber *)width {
  RSDimensions *object = [[RSDimensions alloc] init];
  object.height = height;
  object.length = length;
  object.width = width;
  return object;
}

-(nonnull NSDictionary<NSString *, id> *) toDictionary {
  NSMutableDictionary *properties = [[NSMutableDictionary alloc] init];
  if (self.height != nil) {
    properties[@"height"] = self.height;
  }
  if (self.length != nil) {
    properties[@"length"] = self.length;
  }
  if (self.width != nil) {
    properties[@"width"] = self.width;
  }

  return properties;
}

@end
