/**
 * This client was automatically generated by RudderStack Typewriter. ** Do Not Edit **
 */

#import "RSTypewriterAnalytics.h"
#import "RSTypewriterUtils.h"

@implementation RSTypewriterAnalytics

+ (void)signInFailedWithDimensions:(nullable RSDimensions *)dimensions
id_:(nonnull NSString *)id_
numAttempts:(nullable NSNumber *)numAttempts
rememberMe:(nullable NSNumber *)rememberMe
{
    [RSTypewriterAnalytics signInFailedWithDimensions:dimensions id_:id_ numAttempts:numAttempts rememberMe:rememberMe options:[[RSOption alloc]init]];
}

+ (void)signInFailedWithDimensions:(nullable RSDimensions *)dimensions
id_:(nonnull NSString *)id_
numAttempts:(nullable NSNumber *)numAttempts
rememberMe:(nullable NSNumber *)rememberMe
options:(nullable RSOption *)options
{
    NSMutableDictionary *properties = [[NSMutableDictionary alloc] init];
    if (dimensions != nil) {
      properties[@"dimensions"] = [dimensions toDictionary];
    }
    if (id_ != nil) {
      properties[@"id"] = id_;
    }
    if (numAttempts != nil) {
      properties[@"numAttempts"] = numAttempts;
    }
    if (rememberMe != nil) {
      properties[@"rememberMe"] = rememberMe;
    }

    [[RSClient sharedInstance] track:@"Sign In Failed" properties:properties options:[RSTypewriterUtils withTypewriterContextFields:options]];
}

+ (void)signInSubmittedWithId_:(nonnull NSString *)id_
numAttempts:(nullable NSNumber *)numAttempts
rememberMe:(nullable NSNumber *)rememberMe
{
    [RSTypewriterAnalytics signInSubmittedWithId_:id_ numAttempts:numAttempts rememberMe:rememberMe options:[[RSOption alloc]init]];
}

+ (void)signInSubmittedWithId_:(nonnull NSString *)id_
numAttempts:(nullable NSNumber *)numAttempts
rememberMe:(nullable NSNumber *)rememberMe
options:(nullable RSOption *)options
{
    NSMutableDictionary *properties = [[NSMutableDictionary alloc] init];
    if (id_ != nil) {
      properties[@"id"] = id_;
    }
    if (numAttempts != nil) {
      properties[@"numAttempts"] = numAttempts;
    }
    if (rememberMe != nil) {
      properties[@"rememberMe"] = rememberMe;
    }

    [[RSClient sharedInstance] track:@"Sign In Submitted" properties:properties options:[RSTypewriterUtils withTypewriterContextFields:options]];
}

+ (void)signInSucceededWithId_:(nonnull NSString *)id_
numAttempts:(nullable NSNumber *)numAttempts
rememberMe:(nullable NSNumber *)rememberMe
{
    [RSTypewriterAnalytics signInSucceededWithId_:id_ numAttempts:numAttempts rememberMe:rememberMe options:[[RSOption alloc]init]];
}

+ (void)signInSucceededWithId_:(nonnull NSString *)id_
numAttempts:(nullable NSNumber *)numAttempts
rememberMe:(nullable NSNumber *)rememberMe
options:(nullable RSOption *)options
{
    NSMutableDictionary *properties = [[NSMutableDictionary alloc] init];
    if (id_ != nil) {
      properties[@"id"] = id_;
    }
    if (numAttempts != nil) {
      properties[@"numAttempts"] = numAttempts;
    }
    if (rememberMe != nil) {
      properties[@"rememberMe"] = rememberMe;
    }

    [[RSClient sharedInstance] track:@"Sign In Succeeded" properties:properties options:[RSTypewriterUtils withTypewriterContextFields:options]];
}

+ (void)userSignedOutWithId_:(nonnull NSString *)id_
numAttempts:(nullable NSNumber *)numAttempts
rememberMe:(nullable NSNumber *)rememberMe
{
    [RSTypewriterAnalytics userSignedOutWithId_:id_ numAttempts:numAttempts rememberMe:rememberMe options:[[RSOption alloc]init]];
}

+ (void)userSignedOutWithId_:(nonnull NSString *)id_
numAttempts:(nullable NSNumber *)numAttempts
rememberMe:(nullable NSNumber *)rememberMe
options:(nullable RSOption *)options
{
    NSMutableDictionary *properties = [[NSMutableDictionary alloc] init];
    if (id_ != nil) {
      properties[@"id"] = id_;
    }
    if (numAttempts != nil) {
      properties[@"numAttempts"] = numAttempts;
    }
    if (rememberMe != nil) {
      properties[@"rememberMe"] = rememberMe;
    }

    [[RSClient sharedInstance] track:@"User Signed Out" properties:properties options:[RSTypewriterUtils withTypewriterContextFields:options]];
}

@end
