/**
 * This client was automatically generated by RudderStack Typewriter. ** Do Not Edit **
 */
#import <Foundation/Foundation.h>
#import <Rudder/Rudder.h>
#import "RSDimensions.h"

@interface RSTypewriterAnalytics : NSObject

/// Fired after a user's signin attempt fails to pass validation.
+ (void)signInFailedWithDimensions:(nullable RSDimensions *)dimensions
id_:(nonnull NSString *)id_
numAttempts:(nullable NSNumber *)numAttempts
rememberMe:(nullable NSNumber *)rememberMe;

/// Fired after a user's signin attempt fails to pass validation.
+ (void)signInFailedWithDimensions:(nullable RSDimensions *)dimensions
id_:(nonnull NSString *)id_
numAttempts:(nullable NSNumber *)numAttempts
rememberMe:(nullable NSNumber *)rememberMe
options:(nullable RSOption *)options;

/// Fired when a user submits a sign in, prior to validating that user's login.
+ (void)signInSubmittedWithId_:(nonnull NSString *)id_
numAttempts:(nullable NSNumber *)numAttempts
rememberMe:(nullable NSNumber *)rememberMe;

/// Fired when a user submits a sign in, prior to validating that user's login.
+ (void)signInSubmittedWithId_:(nonnull NSString *)id_
numAttempts:(nullable NSNumber *)numAttempts
rememberMe:(nullable NSNumber *)rememberMe
options:(nullable RSOption *)options;

/// Fired when a user successfully submits a sign in, prior to redirecting into the app.
+ (void)signInSucceededWithId_:(nonnull NSString *)id_
numAttempts:(nullable NSNumber *)numAttempts
rememberMe:(nullable NSNumber *)rememberMe;

/// Fired when a user successfully submits a sign in, prior to redirecting into the app.
+ (void)signInSucceededWithId_:(nonnull NSString *)id_
numAttempts:(nullable NSNumber *)numAttempts
rememberMe:(nullable NSNumber *)rememberMe
options:(nullable RSOption *)options;

/// Fired when a user successfully submits a sign in, prior to redirecting into the app.
+ (void)userSignedOutWithId_:(nonnull NSString *)id_
numAttempts:(nullable NSNumber *)numAttempts
rememberMe:(nullable NSNumber *)rememberMe;

/// Fired when a user successfully submits a sign in, prior to redirecting into the app.
+ (void)userSignedOutWithId_:(nonnull NSString *)id_
numAttempts:(nullable NSNumber *)numAttempts
rememberMe:(nullable NSNumber *)rememberMe
options:(nullable RSOption *)options;

@end
