/**
 * This client was automatically generated by RudderStack Typewriter. ** Do Not Edit **
 */

#import "RSTypewriterSerializable.h"
#import <Rudder/Rudder.h>

@interface RSTypewriterUtils : NSObject

+ (nonnull RSOption *)withTypewriterContextFields:(nullable RSOption *)options;

+ (nonnull NSArray<id> *)toSerializableArray:(nonnull NSArray<id> *) arr;

@end
