/**
 * This client was automatically generated by RudderStack Typewriter. ** Do Not Edit **
 */

#import <Foundation/Foundation.h>

@protocol RSTypewriterSerializable

-(nonnull NSDictionary<NSString *, id> *) toDictionary;

@end
